### ISSUE TITLE
Error with python subprocess.py

### ISSUE THREAD

**Issue by kscott94** [BSSeeker/BSseeker2#27]
I've never had this error while using BSseeker2 before. Any ideas what could be causing it and how to fix it?

Traceback (most recent call last):
  File "/bsseeker2/bs_seeker2-align.py", line 412, in <module>
    options.Output_unmapped_hit
  File "/bsseeker2/bs_align/bs_single_end.py", line 592, in bs_single_end
    'output_file' : CC2T} ])
  File "/bsseeker2/bs_utils/utils.py", line 332, in run_in_parallel
    for i, proc in enumerate([subprocess.Popen(args = shlex.split(cmd), stdout = stdout) for cmd, stdout in commands]):
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by kscott94** [comment]
I did not have an aligner installed. Installed bowtie2 and the issue was resolved

**Comment by guoweilong** [comment]
Thanks for your feedback!
